name: CI
on:
  - pull_request
  - push
jobs:
  lint-and-format:
    name: Lint & format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - run: npm install --ignore-scripts
      - run: npm run format
      - run: npx remark . -qf

  test-parser:
    name: Parser (${{matrix.node}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - lts/*
          - node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: npm install --ignore-scripts
      - run: npm test

  test-packages:
    name: Packages (${{matrix.node}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - lts/*
          - node
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: npm install --ignore-scripts
      - name: Install and test each package
        run: |
          for d in packages/*/; do
            echo "=== $d ==="
            (cd "$d" && npm install --ignore-scripts && npm run build && npm run test-api)
          done
